In [25]:
#올림을 위한 라이브러리 math
import math
import numpy as np
def solution(pros, speeds):
    answer = []
    day = zip(pros, speeds)
    li = []
    for i, j in day:
        li.append(math.ceil((100-i)/j))
    # li.pop(0)
    li2 = np.array(li)
    le =len(li2)
    while le>0:
        print("원본 : ", li2)
        cnt = 0
        li2 = li2-li2[0]
        print("맨 앞숫자로 빼기 : ", li2)
        li2 = np.delete(li2, 0)
        print("맨 앞숫자 제거 : ", li2)
        cnt+=1
        le-=1
        li3= li2
        for i in range(len(li2)):
            if li2[i]<=0:
                cnt+=1
                li3 = np.delete(li3, 0)
                print("그 후 뒤에 뺄 수 있는거 차례차례 제거 : ", li3)
                le-=1
            else:
                break
        answer.append(cnt)
        li2 = li3
        print("--------------------------------")
    
    return answer

In [26]:
progresses = [93, 30, 55]
speeds = [1, 30, 5]
solution(progresses, speeds)

원본 :  [7 3 9]
맨 앞숫자로 빼기 :  [ 0 -4  2]
맨 앞숫자 제거 :  [-4  2]
그 후 뒤에 뺄 수 있는거 차례차례 제거 :  [2]
--------------------------------
원본 :  [2]
맨 앞숫자로 빼기 :  [0]
맨 앞숫자 제거 :  []
--------------------------------


[2, 1]

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
a[1]

2

In [5]:
len(a)

5

In [6]:
for i in range(len(a)):
    print(i)

0
1
2
3
4


In [27]:
progresses = [95, 90, 99, 99, 80, 99]
speeds = [1, 1, 1, 1, 1, 1]
solution(progresses, speeds)

원본 :  [ 5 10  1  1 20  1]
맨 앞숫자로 빼기 :  [ 0  5 -4 -4 15 -4]
맨 앞숫자 제거 :  [ 5 -4 -4 15 -4]
--------------------------------
원본 :  [ 5 -4 -4 15 -4]
맨 앞숫자로 빼기 :  [ 0 -9 -9 10 -9]
맨 앞숫자 제거 :  [-9 -9 10 -9]
그 후 뒤에 뺄 수 있는거 차례차례 제거 :  [-9 10 -9]
그 후 뒤에 뺄 수 있는거 차례차례 제거 :  [10 -9]
--------------------------------
원본 :  [10 -9]
맨 앞숫자로 빼기 :  [  0 -19]
맨 앞숫자 제거 :  [-19]
그 후 뒤에 뺄 수 있는거 차례차례 제거 :  []
--------------------------------


[1, 3, 2]

In [22]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [23]:
a= np.delete(a, 0)
a

array([2, 3, 4, 5])

In [24]:
a= np.delete(a, 0)
a

array([3, 4, 5])